name: build lambda layer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
    AWS_REGION: "eu-north-1"
permissions:
    id-token: write
    contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: install requirements
        run: |
          python -m pip install -r requirements.txt -t python/
          zip -r layer.zip python/
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: publish lambda
        run: |
          aws lambda publish-layer-version --layer-name translate-lambda --zip-file fileb://layer.zip --compatible-runtimes python3.12
